defmodule WhoThere.Repo.Migrations.AddWhoThereTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:daily_analytics, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :date, :date, null: false
      add :unique_visitors, :bigint, default: 0
      add :page_views, :bigint, default: 0
      add :sessions, :bigint, default: 0
      add :bounced_sessions, :bigint, default: 0
      add :total_duration_seconds, :bigint, default: 0
      add :bot_requests, :bigint, default: 0
      add :human_requests, :bigint, default: 0
      add :top_pages, :map, default: %{}
      add :top_referrers, :map, default: %{}
      add :countries, :map, default: %{}
      add :devices, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:daily_analytics, [:tenant_id, :date, :page_views])

    create index(:daily_analytics, [:tenant_id, :date, :unique_visitors])

    create index(:daily_analytics, [:tenant_id, :date], unique: true)

    create unique_index(:daily_analytics, [:tenant_id, :date],
             name: "daily_analytics_unique_analytics_per_tenant_date_index"
           )

    create table(:analytics_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :session_fingerprint, :text, null: false
      add :user_id, :text
      add :started_at, :utc_datetime_usec, null: false
      add :last_seen_at, :utc_datetime_usec, null: false
      add :duration_seconds, :bigint, default: 0
      add :page_views, :bigint, default: 1
      add :entry_path, :text
      add :exit_path, :text
      add :referrer, :text
      add :country_code, :text
      add :city, :text
      add :device_type, :text
      add :is_bot, :boolean, default: false
      add :is_bounce, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:analytics_sessions, [:tenant_id, :last_seen_at])

    create index(:analytics_sessions, [:tenant_id, :user_id], where: "user_id IS NOT NULL")

    create index(:analytics_sessions, [:tenant_id, :is_bot])

    create index(:analytics_sessions, [:tenant_id, :session_fingerprint], unique: true)

    create index(:analytics_sessions, [:tenant_id, :started_at])

    create unique_index(:analytics_sessions, [:tenant_id, :session_fingerprint],
             name: "analytics_sessions_unique_session_per_tenant_index"
           )

    create table(:analytics_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :event_type, :text, null: false
      add :timestamp, :utc_datetime_usec, null: false

      add :session_id,
          references(:analytics_sessions,
            column: :id,
            name: "analytics_events_session_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :user_id, :text
      add :path, :text, null: false
      add :method, :text
      add :status_code, :bigint
      add :duration_ms, :bigint
      add :user_agent, :text
      add :device_type, :text
      add :ip_address, :text
      add :country_code, :text
      add :city, :text
      add :referrer, :text
      add :bot_name, :text
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:analytics_events, [:tenant_id, :bot_name], where: "event_type = 'bot_traffic'")

    create index(:analytics_events, [:tenant_id, :session_id], where: "session_id IS NOT NULL")

    create index(:analytics_events, [:tenant_id, :path, :timestamp])

    create index(:analytics_events, [:tenant_id, :event_type, :timestamp])

    create index(:analytics_events, [:tenant_id, :timestamp])

    create unique_index(:analytics_events, [:tenant_id, :timestamp, :path, :session_id],
             name: "analytics_events_unique_event_index",
             where: "(session_id IS NOT NULL)"
           )

    create table(:analytics_configurations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :enabled, :boolean, default: true
      add :collect_user_agents, :boolean, default: true
      add :collect_referrers, :boolean, default: true
      add :collect_geolocation, :boolean, default: true
      add :anonymize_ips, :boolean, default: true
      add :exclude_admin_routes, :boolean, default: true
      add :exclude_patterns, {:array, :text}, default: []
      add :session_timeout_minutes, :bigint, default: 30
      add :data_retention_days, :bigint, default: 365
      add :bot_detection_enabled, :boolean, default: true
      add :presence_integration, :boolean, default: false
      add :dashboard_enabled, :boolean, default: true
      add :d3_visualizations_enabled, :boolean, default: true
      add :proxy_header_detection, :boolean, default: true
      add :live_view_deduplication, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:analytics_configurations, [:tenant_id], unique: true)

    create unique_index(:analytics_configurations, [:tenant_id],
             name: "analytics_configurations_unique_config_per_tenant_index"
           )
  end

  def down do
    drop_if_exists unique_index(:analytics_configurations, [:tenant_id],
                     name: "analytics_configurations_unique_config_per_tenant_index"
                   )

    drop_if_exists index(:analytics_configurations, [:tenant_id])

    drop table(:analytics_configurations)

    drop_if_exists unique_index(:analytics_events, [:tenant_id, :timestamp, :path, :session_id],
                     name: "analytics_events_unique_event_index"
                   )

    drop constraint(:analytics_events, "analytics_events_session_id_fkey")

    drop_if_exists index(:analytics_events, [:tenant_id, :timestamp])

    drop_if_exists index(:analytics_events, [:tenant_id, :event_type, :timestamp])

    drop_if_exists index(:analytics_events, [:tenant_id, :path, :timestamp])

    drop_if_exists index(:analytics_events, [:tenant_id, :session_id])

    drop_if_exists index(:analytics_events, [:tenant_id, :bot_name])

    drop table(:analytics_events)

    drop_if_exists unique_index(:analytics_sessions, [:tenant_id, :session_fingerprint],
                     name: "analytics_sessions_unique_session_per_tenant_index"
                   )

    drop_if_exists index(:analytics_sessions, [:tenant_id, :started_at])

    drop_if_exists index(:analytics_sessions, [:tenant_id, :session_fingerprint])

    drop_if_exists index(:analytics_sessions, [:tenant_id, :is_bot])

    drop_if_exists index(:analytics_sessions, [:tenant_id, :user_id])

    drop_if_exists index(:analytics_sessions, [:tenant_id, :last_seen_at])

    drop table(:analytics_sessions)

    drop_if_exists unique_index(:daily_analytics, [:tenant_id, :date],
                     name: "daily_analytics_unique_analytics_per_tenant_date_index"
                   )

    drop_if_exists index(:daily_analytics, [:tenant_id, :date])

    drop_if_exists index(:daily_analytics, [:tenant_id, :date, :unique_visitors])

    drop_if_exists index(:daily_analytics, [:tenant_id, :date, :page_views])

    drop table(:daily_analytics)
  end
end
